// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lppawtyqvnmhqvuepmth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcGF3dHlxdm5taHF2dWVwbXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzgzMjgsImV4cCI6MjA2NjM1NDMyOH0.4zSuApaDhyswQPfdpKlGxkjfCrfR5KnpHev8kM1IaY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);